
package com.training.prodsvc;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductServiceImpl", targetNamespace = "http://prodsvc.training.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "getProductInfoReturn", targetNamespace = "http://prodsvc.training.com")
    @RequestWrapper(localName = "getProductInfo", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.GetProductInfo")
    @ResponseWrapper(localName = "getProductInfoResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.GetProductInfoResponse")
    public List<String> getProductInfo();

    /**
     * 
     * @param prod
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "deleteProductReturn", targetNamespace = "http://prodsvc.training.com")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.DeleteProductResponse")
    public String deleteProduct(
        @WebParam(name = "prod", targetNamespace = "http://prodsvc.training.com")
        Product prod);

    /**
     * 
     * @param prod
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "addProductReturn", targetNamespace = "http://prodsvc.training.com")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.AddProductResponse")
    public String addProduct(
        @WebParam(name = "prod", targetNamespace = "http://prodsvc.training.com")
        Product prod);

    /**
     * 
     * @param prod
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "updateProductReturn", targetNamespace = "http://prodsvc.training.com")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://prodsvc.training.com", className = "com.training.prodsvc.UpdateProductResponse")
    public String updateProduct(
        @WebParam(name = "prod", targetNamespace = "http://prodsvc.training.com")
        Product prod);

}
